language: node_js
node_js:
  - "6.0.0"

before_script:
  - npm install
script:
  - npm start
  

deploy:
  provider: heroku
  api_key: 1848b0a2-8601-4228-8e9f-4dff65fe47d5
  app: typescript-rogue-mapper
  on:
    all_branches: true
